#!/bin/bash

echo "GitHub MCP サーバーのセットアップ"
echo "================================"
echo ""
echo "1. GitHub Personal Access Tokenを作成してください："
echo "   https://github.com/settings/tokens/new"
echo ""
echo "必要な権限："
echo "- repo (Full control of private repositories)"
echo "- read:org (Read org and team membership)"
echo "- read:user (Read all user profile data)"
echo ""
echo "2. 作成したトークンを以下のファイルに設定してください："
echo "   ~/Library/Application Support/Claude/claude_desktop_config.json"
echo ""
echo "   \"GITHUB_PERSONAL_ACCESS_TOKEN\": \"your-token-here\""
echo ""
echo "3. Claude Desktopを再起動してください"
echo ""
echo "設定ファイルの場所："
echo "~/Library/Application Support/Claude/claude_desktop_config.json"