name: Claude Code
on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited]

jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
      - uses: anthropic/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}